export const jwtConstants = {
	secret: 'THIS IS ARBITRARY SECRET. NEED TO BE CALLED BY ENVIRONMENT VARIABLE.',
	signupSecret: 'THIS IS SIGNUP SECRET. IT ALSO NEED TO BE CALLED BY ENVIRIONMENT VARIABLE.',
	loginSecret: 'THIS SECRET IS USED WHEN LOG IN EVENT. IT ALSO NEED TO BE CALLED BY ENVIRONMENT VARIABLE.',
};
